woowacourse-teams/2022-moamoa

backend/src/main/java/com/woowacourse/moamoa/common/config/WebConfig.java
backend/src/test/java/com/woowacourse/acceptance/AcceptanceTest.java

CORS 허용
`HTTP 테### CORS 허용 여부를 확인하는 테스트 작성
`HTTP 테스트 요청`
```
OPTIONS /api/studies HTTP/1.1
Origin: https://xxx.com
Access-Control-Request-Method: GET
```
`HTTP 테스트 응답`
* 테스트 성공 시 200
* 테스트 실패 시 403
close #28

[BE] issue28: CORS 허용

---

.github/workflows/backend.yml

백엔드 ci 세팅
빌드, 테스트 실행 후 결과 슬랙으로 알림
close #7

[BE] issue7: 백엔드 ci 세팅

---

frontend/.eslintrc.json

[FE] issue35: Lint 오류 해결

---

.github/workflows/frontend.yml

프론트엔드 github actions 사용한 CI 설정
close #71

[FE] issue71: 프론트엔드 CI 설정

---

backend/src/test/java/com/woowacourse/acceptance/study/GettingStudiesAcceptanceTest.java
backend/src/test/java/com/woowacourse/acceptance/study/SearchingStudiesAcceptanceTest.java

인수테스트에서 param -> queryParam 사용
param 보다 queryParam 이 쿼리 파라미터 라는 것을 명시적으로 나타내므로 수정
close #49

[BE] issue49: param -> queryParam 사용

---

frontend/src/api/getStudyDetail.ts
frontend/src/pages/detail-page/DetailPage.tsx
frontend/src/pages/detail-page/hooks/useFetchDetail.ts

api 명세에 따라 수정
상세 페이지 조회시 {study : {}} -> {}로 변경

[FE] hotfix: api 명세에 따라 수정

---

backend/src/main/java/com/woowacourse/moamoa/review/controller/ReviewController.java
backend/src/main/java/com/woowacourse/moamoa/review/domain/AssociatedStudy.java
backend/src/main/java/com/woowacourse/moamoa/review/domain/Review.java
backend/src/main/java/com/woowacourse/moamoa/review/domain/repository/JpaReviewRepository.java
backend/src/main/java/com/woowacourse/moamoa/review/domain/repository/ReviewRepository.java
backend/src/main/java/com/woowacourse/moamoa/review/service/ReviewService.java
backend/src/main/java/com/woowacourse/moamoa/review/service/response/ReviewResponse.java
backend/src/main/java/com/woowacourse/moamoa/review/service/response/ReviewsResponse.java
backend/src/test/java/com/woowacourse/acceptance/review/GettingReviewsAcceptanceTest.java
backend/src/test/java/com/woowacourse/moamoa/review/domain/repository/ReviewRepositoryTest.java
backend/src/test/java/com/woowacourse/moamoa/review/service/ReviewServiceTest.java
backend/src/test/resources/application.yml
backend/src/test/resources/data.sql
backend/src/test/resources/schema.sql

스터디 후기 목록 조회
스터디 후기를 조회할 수 있다.
(Member 정보와 전체 후기 수를 함께 조회한다.)
close #108

[BE] issue108: 스터디 후기 조회

---

frontend/src/mocks/handlers.ts

[FE] hofix: 잘못된 import문 수정

---

frontend/env/.env.local
frontend/package.json
frontend/src/custom-types/index.ts
frontend/src/pages/detail-page/DetailPage.tsx
frontend/src/pages/detail-page/components/study-float-box/StudyFloatBox.tsx
frontend/src/pages/detail-page/components/study-review-section/StudyReviewSection.tsx
frontend/src/pages/detail-page/components/study-wide-float-box/StudyWideFloatBox.tsx
frontend/src/pages/main-page/MainPage.tsx
frontend/src/pages/my-study-page/components/my-study-card-list-section/MyStudyCardListSection.stories.tsx
frontend/src/pages/my-study-page/components/my-study-card/MyStudyCard.tsx
frontend/src/pages/study-room-page/components/side-menu/SideMenu.stories.tsx
frontend/src/utils/dates.ts

이슈에 기록한 여러가지 에러를 수정했습니다.
close #197

[FE] 여러가지 오류 수정

---

backend/src/docs/asciidoc/index.adoc
backend/src/test/java/com/woowacourse/acceptance/member/MemberAcceptanceTest.java
backend/src/test/java/com/woowacourse/acceptance/study/CreatingStudyAcceptanceTest.java

REST Docs API 명세 업데이트 및 header, request, response 추가
close #205

[BE] REST Docs API 수정 및 업데이트

---

frontend/env/.env.local
frontend/package-lock.json
frontend/package.json
frontend/src/components/arrow-button/ArrowButton.tsx
frontend/src/index.tsx
frontend/src/layout/header/Header.tsx
frontend/src/layout/header/components/search-bar/SearchBar.tsx
frontend/src/pages/create-study-page/CreateStudyPage.tsx
frontend/src/pages/create-study-page/components/subject/Subject.style.tsx
frontend/src/pages/create-study-page/components/subject/Subject.tsx
frontend/src/pages/create-study-page/components/tag/Tag.tsx
frontend/src/pages/detail-page/components/study-float-box/StudyFloatBox.tsx
frontend/src/pages/detail-page/components/study-member-section/StudyMemberSection.tsx
frontend/src/pages/my-study-page/components/my-study-card/MyStudyCard.tsx
frontend/src/styles/Globalstyles.tsx
frontend/webpack/webpack.common.js

QA에서 발견한 오류들을 수정한다
- 싴, 뷁 등 나눔폰트에서 지원되지 않는 글자가 있기 때문에 폰트를 변경한다
- 스터디 디테일 페이지에서 인원이 7명일때 더보기 버튼이 보이지 않는 오류를 수정한다
- 스터디 생성시 etc(미분류) 태그를 기본으로 선택하도록 수정한다. 선택 안함은 제거한다
close #226

[FE] issue226: 각종 오류 수정

---

frontend/src/api/postLogin.ts
frontend/src/mocks/tokenHandlers.ts

api/auth/login/token -> api/auth/login

[FE] 로그인 경로 수정

---

backend/src/main/java/com/woowacourse/moamoa/auth/controller/AuthController.java

Refresh Token 핫픽스
fix: sameSite("None") 추가

[BE] issue229: Refresh Token 핫픽스

---

frontend/src/auth/accessToken.ts

accessToken 저장 위치 세션 스토리지로 변경
#261 
close #261

[FE] issue261: accessToken 저장 위치 변경

---

backend/src/main/java/com/woowacourse/moamoa/referenceroom/query/LinkDao.java
backend/src/test/java/com/woowacourse/acceptance/test/referenceroom/ReferenceRoomAcceptanceTest.java

[BE] refactor: 링크 조회 로직 수정

---

backend/build.gradle
backend/src/main/java/com/woowacourse/moamoa/auth/controller/AuthenticatedMemberResolver.java
backend/src/test/java/com/woowacourse/moamoa/WebMVCTest.java

- SonarQube에 Postgresql DB를 연동한다.
#290

[BE] issue290: SonarQube PostgreSQL 연동

---

backend/src/main/java/com/woowacourse/moamoa/member/query/data/OwnerData.java
backend/src/main/java/com/woowacourse/moamoa/study/query/StudyDetailsDao.java
backend/src/main/java/com/woowacourse/moamoa/study/query/data/StudyDetailsData.java
backend/src/main/java/com/woowacourse/moamoa/study/query/data/StudyDetailsDataBuilder.java
backend/src/main/java/com/woowacourse/moamoa/study/service/response/StudyDetailResponse.java
backend/src/test/java/com/woowacourse/moamoa/study/controller/SearchingStudyControllerTest.java
backend/src/test/java/com/woowacourse/moamoa/study/query/StudyDetailsDaoTest.java

[BE] fix: 스터디장 또한 참여한 스터디 개수 표시

---

frontend/src/constants.ts
frontend/src/pages/study-room-page/tabs/community-tab-panel/components/article-list/ArticleList.tsx
frontend/src/pages/study-room-page/tabs/notice-tab-panel/NoticeTabPanel.tsx
frontend/src/pages/study-room-page/tabs/notice-tab-panel/components/article-list/ArticleList.tsx
frontend/src/pages/study-room-page/tabs/notice-tab-panel/components/edit/Edit.tsx
frontend/src/pages/study-room-page/tabs/notice-tab-panel/components/publish/Publish.tsx
frontend/src/pages/study-room-page/tabs/notice-tab-panel/hooks/usePermission.ts

1. 공지사항은 스터디장만 게시글 작성 하도록 한다
close #312

[FE] issue312: 게시판 기능 개선

---

backend/src/main/java/com/woowacourse/moamoa/common/advice/CommonControllerAdvice.java
backend/src/main/java/com/woowacourse/moamoa/study/domain/Study.java
backend/src/main/java/com/woowacourse/moamoa/study/service/StudyService.java
backend/src/main/java/com/woowacourse/moamoa/study/service/exception/InvalidUpdatingException.java
backend/src/test/java/com/woowacourse/acceptance/test/study/UpdatingStudyAcceptanceTest.java

[BE] issue300: 스터디 update 로직 수정

---

backend/src/main/java/com/woowacourse/moamoa/study/service/StudyParticipantService.java

[BE] : 동시성 문제

---

backend/src/main/java/com/woowacourse/moamoa/study/query/MyStudyDao.java
backend/src/main/java/com/woowacourse/moamoa/study/query/StudySummaryDao.java

Study 쪽 쿼리 개선
- 이전에 이미 진행된 case문 -> count 문 에 대한 개선은 제외하고 진행한다.
- 검색시 title 이 없는 경우에는 해당 where 조건을 제외한다.
- distinct 문을 제외하고 PK 를 사용한 group by 로 중복을 제거하여 인덱스를 탈 수 있도록 수정한다.
close #377

[BE] issue377: Study 쪽 쿼리 개선

---

frontend/src/pages/my-study-page/components/my-study-card/MyStudyCard.tsx

이전에 잘못 머지한 브랜치에서 버그를 고쳤었는데,  
이 브랜치를 revert하면서 메인에 버그가 다시 발생했습니다.  
이를 수정했습니다.  
close #382

fix: tags null check

---

.github/workflows/deploy-backend-dev.yml

chore: 배포 스크립트 수정

---

.github/workflows/deploy-backend-dev.yml

배포 스크립트 수정

---

backend/build.gradle

Spring-actuator 설정
Spring Application 모니터링을 위해 actuator 를 설정한다.
close #396

[BE] issue396: Spring-actuator 설정

---

frontend/src/api/my-study/typeChecker.ts
frontend/src/api/studies/typeChecker.ts

- main page 스터디 목록
- my study page 스터디 목록 
-> 타입 충돌 오류 수정

fix: api 타입 수정

---

backend/src/main/java/com/woowacourse/moamoa/study/service/request/StudyRequest.java
backend/src/test/java/com/woowacourse/acceptance/test/study/CreatingStudyAcceptanceTest.java

태그가 없는 경우 예외가 발생할 수 있도록 validation을 추가해주었습니다.

[BE] hotfix: 태그가 없는 경우에 대한 검사 추가

---

backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthConfig.java

- 스터디 방을 전체 개방하기로 하였으므로, auth가 필요한 path를 제거합니다. 
📌 컨트롤러 및 인터셉터 path에 남아있는 인증이 있는지 확인부탁드립니다.

fix: auth request path 제거

---

backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthConfig.java
backend/src/main/java/com/woowacourse/moamoa/studyroom/service/request/ArticleRequest.java

Article 사이즈를 50_000 으로 변경
Article 사이즈를 프런트 요청에 의해 50_000 제한으로 변경합니다.
DB 테이블은 `longtext` 로 저장하는데 문제가 없을 것 같습니다.

[BE] hotfix: Article 사이즈 변경

---

backend/src/main/java/com/woowacourse/moamoa/auth/config/AuthConfig.java
backend/src/main/java/com/woowacourse/moamoa/studyroom/service/request/ArticleRequest.java

Reverts woowacourse-teams/2022-moamoa#434

Revert "[BE] hotfix: Article 사이즈 변경"

---

backend/src/docs/asciidoc/index.adoc
backend/src/test/java/com/woowacourse/acceptance/document/TempArticleDocument.java
backend/src/test/java/com/woowacourse/acceptance/steps/TempCommunityArticleRelatedStep.java
backend/src/test/java/com/woowacourse/acceptance/test/studyroom/TempCommunityArticleAcceptanceTest.java

test: 임시글 공개 API 문서 추가

---

backend/src/docs/asciidoc/index.adoc
backend/src/main/java/com/woowacourse/moamoa/study/controller/StudyParticipantController.java
backend/src/test/java/com/woowacourse/acceptance/document/ReviewDocument.java
backend/src/test/java/com/woowacourse/acceptance/document/StudyDocument.java
backend/src/test/java/com/woowacourse/acceptance/steps/StudyRelatedSteps.java
backend/src/test/java/com/woowacourse/acceptance/test/comment/CommunityCommentAcceptanceTest.java
backend/src/test/java/com/woowacourse/acceptance/test/study/GettingStudyDetailsAcceptanceTest.java
backend/src/test/java/com/woowacourse/acceptance/test/study/StudyParticipantAcceptanceTest.java
backend/src/test/java/com/woowacourse/acceptance/test/study/UpdatingStudyAcceptanceTest.java
backend/src/test/java/com/woowacourse/acceptance/test/studyroom/ReviewsAcceptanceTest.java
backend/src/test/java/com/woowacourse/moamoa/study/controller/StudyParticipantControllerTest.java

fix: API 문서 오류 수정
